function [ midimain, notematrix ] = loadmidi( path )

midimain = javaObjectEDT('MidiMain', path);
notematrix = midimain.getNoteMatrix;

% notematrixlabels = [    '1. track number', ...
%                         '2. channel number', ...
%                         '3. note number', ...
%                         '4. note_on velocity', ...
%                         '5. note_on time (tick)', ...
%                         '6. note_off time (tick)', ...
%                         '7. note_on event index', ...
%                         '8. note_off event index'
%                         ];
[~, I] = sort(notematrix(:,5));
notematrix = notematrix(I,:);

end
